--counties
INSERT INTO e_vote.counties (name, created_at, created_by, updated_at, updated_by) VALUES 
('Mombasa', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kwale', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kilifi', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Tana River', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Lamu', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Taita Taveta', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Garissa', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Wajir', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Mandera', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Marsabit', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Isiolo', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Meru', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Tharaka Nithi', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Embu', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kitui', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Machakos', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Makueni', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Nyandarua', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Nyeri', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kirinyaga', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Murang''a', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kiambu', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Turkana', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('West Pokot', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Samburu', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Trans Nzoia', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Uasin Gishu', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Elgeyo Marakwet', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Nandi', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Baringo', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Laikipia', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Nakuru', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Narok', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kajiado', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kericho', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Bomet', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kakamega', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Vihiga', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Bungoma', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Busia', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Siaya', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kisumu', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Homa Bay', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Migori', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Kisii', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Nyamira', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL),
('Nairobi', CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, NULL);

--constituences
INSERT INTO e_vote.constituencies (county_id, name, created_at, created_by, updated_by) VALUES 
-- Mombasa County (1)
(1, 'Changamwe', CURRENT_TIMESTAMP, NULL, NULL),
(1, 'Jomvu', CURRENT_TIMESTAMP, NULL, NULL),
(1, 'Kisauni', CURRENT_TIMESTAMP, NULL, NULL),
(1, 'Nyali', CURRENT_TIMESTAMP, NULL, NULL),
(1, 'Likoni', CURRENT_TIMESTAMP, NULL, NULL),
(1, 'Mvita', CURRENT_TIMESTAMP, NULL, NULL),
(1, 'Shanzu', CURRENT_TIMESTAMP, NULL, NULL),

-- Kwale County (2)
(2, 'Msambweni', CURRENT_TIMESTAMP, NULL, NULL),
(2, 'Lungalunga', CURRENT_TIMESTAMP, NULL, NULL),
(2, 'Matuga', CURRENT_TIMESTAMP, NULL, NULL),
(2, 'Kinango', CURRENT_TIMESTAMP, NULL, NULL),

-- Kilifi County (3)
(3, 'Kilifi North', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'Kilifi South', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'Kaloleni', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'Rabai', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'Ganze', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'Malindi', CURRENT_TIMESTAMP, NULL, NULL),
(3, 'Magarini', CURRENT_TIMESTAMP, NULL, NULL),

-- Tana River County (4)
(4, 'Garsen', CURRENT_TIMESTAMP, NULL, NULL),
(4, 'Galole', CURRENT_TIMESTAMP, NULL, NULL),
(4, 'Bura', CURRENT_TIMESTAMP, NULL, NULL),

-- Lamu County (5)
(5, 'Lamu East', CURRENT_TIMESTAMP, NULL, NULL),
(5, 'Lamu West', CURRENT_TIMESTAMP, NULL, NULL),

-- Taita Taveta County (6)
(6, 'Taveta', CURRENT_TIMESTAMP, NULL, NULL),
(6, 'Wundanyi', CURRENT_TIMESTAMP, NULL, NULL),
(6, 'Mwatate', CURRENT_TIMESTAMP, NULL, NULL),
(6, 'Voi', CURRENT_TIMESTAMP, NULL, NULL),

-- Garissa County (7)
(7, 'Garissa Township', CURRENT_TIMESTAMP, NULL, NULL),
(7, 'Balambala', CURRENT_TIMESTAMP, NULL, NULL),
(7, 'Lagdera', CURRENT_TIMESTAMP, NULL, NULL),
(7, 'Dadaab', CURRENT_TIMESTAMP, NULL, NULL),
(7, 'Fafi', CURRENT_TIMESTAMP, NULL, NULL),
(7, 'Ijara', CURRENT_TIMESTAMP, NULL, NULL),

-- Wajir County (8)
(8, 'Wajir North', CURRENT_TIMESTAMP, NULL, NULL),
(8, 'Wajir East', CURRENT_TIMESTAMP, NULL, NULL),
(8, 'Tarbaj', CURRENT_TIMESTAMP, NULL, NULL),
(8, 'Wajir West', CURRENT_TIMESTAMP, NULL, NULL),
(8, 'Wajir South', CURRENT_TIMESTAMP, NULL, NULL),
(8, 'Habaswein', CURRENT_TIMESTAMP, NULL, NULL),
(8, 'Eldas', CURRENT_TIMESTAMP, NULL, NULL),

-- Mandera County (9)
(9, 'Mandera West', CURRENT_TIMESTAMP, NULL, NULL),
(9, 'Banissa', CURRENT_TIMESTAMP, NULL, NULL),
(9, 'Mandera North', CURRENT_TIMESTAMP, NULL, NULL),
(9, 'Mandera South', CURRENT_TIMESTAMP, NULL, NULL),
(9, 'Mandera East', CURRENT_TIMESTAMP, NULL, NULL),
(9, 'Lafey', CURRENT_TIMESTAMP, NULL, NULL),

-- Marsabit County (10)
(10, 'Moyale', CURRENT_TIMESTAMP, NULL, NULL),
(10, 'North Horr', CURRENT_TIMESTAMP, NULL, NULL),
(10, 'Saku', CURRENT_TIMESTAMP, NULL, NULL),
(10, 'Laisamis', CURRENT_TIMESTAMP, NULL, NULL),

-- Isiolo County (11)
(11, 'Isiolo North', CURRENT_TIMESTAMP, NULL, NULL),
(11, 'Isiolo South', CURRENT_TIMESTAMP, NULL, NULL),

-- Meru County (12)
(12, 'Igembe South', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'Igembe Central', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'Igembe North', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'Tigania West', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'Tigania East', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'North Imenti', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'Buuri', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'Central Imenti', CURRENT_TIMESTAMP, NULL, NULL),
(12, 'South Imenti', CURRENT_TIMESTAMP, NULL, NULL),

-- Tharaka Nithi County (13)
(13, 'Maara', CURRENT_TIMESTAMP, NULL, NULL),
(13, 'Chuka/Igambang''ombe', CURRENT_TIMESTAMP, NULL, NULL),
(13, 'Tharaka', CURRENT_TIMESTAMP, NULL, NULL),

-- Embu County (14)
(14, 'Manyatta', CURRENT_TIMESTAMP, NULL, NULL),
(14, 'Runyenjes', CURRENT_TIMESTAMP, NULL, NULL),
(14, 'Mbeere South', CURRENT_TIMESTAMP, NULL, NULL),
(14, 'Mbeere North', CURRENT_TIMESTAMP, NULL, NULL),

-- Kitui County (15)
(15, 'Mwingi North', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Mwingi West', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Mwingi Central', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Kitui West', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Kitui Rural', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Kitui Central', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Kitui East', CURRENT_TIMESTAMP, NULL, NULL),
(15, 'Kitui South', CURRENT_TIMESTAMP, NULL, NULL),

-- Machakos County (16)
(16, 'Masinga', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Yatta', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Kangundo', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Matungulu', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Kathiani', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Mavoko', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Machakos Town', CURRENT_TIMESTAMP, NULL, NULL),
(16, 'Mwala', CURRENT_TIMESTAMP, NULL, NULL),

-- Makueni County (17)
(17, 'Mbooni', CURRENT_TIMESTAMP, NULL, NULL),
(17, 'Kilome', CURRENT_TIMESTAMP, NULL, NULL),
(17, 'Kaiti', CURRENT_TIMESTAMP, NULL, NULL),
(17, 'Makueni', CURRENT_TIMESTAMP, NULL, NULL),
(17, 'Kibwezi West', CURRENT_TIMESTAMP, NULL, NULL),
(17, 'Kibwezi East', CURRENT_TIMESTAMP, NULL, NULL),

-- Nyandarua County (18)
(18, 'Kinangop', CURRENT_TIMESTAMP, NULL, NULL),
(18, 'Kipipiri', CURRENT_TIMESTAMP, NULL, NULL),
(18, 'Ol Kalou', CURRENT_TIMESTAMP, NULL, NULL),
(18, 'Ol Jorok', CURRENT_TIMESTAMP, NULL, NULL),
(18, 'Ndaragwa', CURRENT_TIMESTAMP, NULL, NULL),

-- Nyeri County (19)
(19, 'Tetu', CURRENT_TIMESTAMP, NULL, NULL),
(19, 'Kieni', CURRENT_TIMESTAMP, NULL, NULL),
(19, 'Mathira', CURRENT_TIMESTAMP, NULL, NULL),
(19, 'Othaya', CURRENT_TIMESTAMP, NULL, NULL),
(19, 'Mukurweini', CURRENT_TIMESTAMP, NULL, NULL),
(19, 'Nyeri Town', CURRENT_TIMESTAMP, NULL, NULL),

-- Kirinyaga County (20)
(20, 'Mwea', CURRENT_TIMESTAMP, NULL, NULL),
(20, 'Gichugu', CURRENT_TIMESTAMP, NULL, NULL),
(20, 'Ndia', CURRENT_TIMESTAMP, NULL, NULL),
(20, 'Kirinyaga Central', CURRENT_TIMESTAMP, NULL, NULL),

-- Murang''a County (21)
(21, 'Kangema', CURRENT_TIMESTAMP, NULL, NULL),
(21, 'Mathioya', CURRENT_TIMESTAMP, NULL, NULL),
(21, 'Kiharu', CURRENT_TIMESTAMP, NULL, NULL),
(21, 'Kigumo', CURRENT_TIMESTAMP, NULL, NULL),
(21, 'Maragwa', CURRENT_TIMESTAMP, NULL, NULL),
(21, 'Kandara', CURRENT_TIMESTAMP, NULL, NULL),
(21, 'Gatanga', CURRENT_TIMESTAMP, NULL, NULL),

-- Kiambu County (22)
(22, 'Gatundu South', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Gatundu North', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Juja', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Thika Town', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Ruiru', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Githunguri', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Kiambu', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Kiambaa', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Kabete', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Kikuyu', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Limuru', CURRENT_TIMESTAMP, NULL, NULL),
(22, 'Lari', CURRENT_TIMESTAMP, NULL, NULL),

-- Turkana County (23)
(23, 'Turkana North', CURRENT_TIMESTAMP, NULL, NULL),
(23, 'Turkana West', CURRENT_TIMESTAMP, NULL, NULL),
(23, 'Turkana Central', CURRENT_TIMESTAMP, NULL, NULL),
(23, 'Loima', CURRENT_TIMESTAMP, NULL, NULL),
(23, 'Turkana South', CURRENT_TIMESTAMP, NULL, NULL),
(23, 'Turkana East', CURRENT_TIMESTAMP, NULL, NULL),

-- West Pokot County (24)
(24, 'Kapenguria', CURRENT_TIMESTAMP, NULL, NULL),
(24, 'Sigor', CURRENT_TIMESTAMP, NULL, NULL),
(24, 'Kacheliba', CURRENT_TIMESTAMP, NULL, NULL),
(24, 'Pokot South', CURRENT_TIMESTAMP, NULL, NULL),

-- Samburu County (25)
(25, 'Samburu West', CURRENT_TIMESTAMP, NULL, NULL),
(25, 'Samburu North', CURRENT_TIMESTAMP, NULL, NULL),
(25, 'Samburu East', CURRENT_TIMESTAMP, NULL, NULL),

-- Trans Nzoia County (26)
(26, 'Kwanza', CURRENT_TIMESTAMP, NULL, NULL),
(26, 'Endebess', CURRENT_TIMESTAMP, NULL, NULL),
(26, 'Saboti', CURRENT_TIMESTAMP, NULL, NULL),
(26, 'Kiminini', CURRENT_TIMESTAMP, NULL, NULL),
(26, 'Cherangany', CURRENT_TIMESTAMP, NULL, NULL),

-- Uasin Gishu County (27)
(27, 'Soy', CURRENT_TIMESTAMP, NULL, NULL),
(27, 'Turbo', CURRENT_TIMESTAMP, NULL, NULL),
(27, 'Moiben', CURRENT_TIMESTAMP, NULL, NULL),
(27, 'Ainabkoi', CURRENT_TIMESTAMP, NULL, NULL),
(27, 'Kapseret', CURRENT_TIMESTAMP, NULL, NULL),
(27, 'Kesses', CURRENT_TIMESTAMP, NULL, NULL),

-- Elgeyo Marakwet County (28)
(28, 'Marakwet West', CURRENT_TIMESTAMP, NULL, NULL),
(28, 'Marakwet East', CURRENT_TIMESTAMP, NULL, NULL),
(28, 'Keiyo South', CURRENT_TIMESTAMP, NULL, NULL),
(28, 'Keiyo North', CURRENT_TIMESTAMP, NULL, NULL),

-- Nandi County (29)
(29, 'Tinderet', CURRENT_TIMESTAMP, NULL, NULL),
(29, 'Aldai', CURRENT_TIMESTAMP, NULL, NULL),
(29, 'Nandi Hills', CURRENT_TIMESTAMP, NULL, NULL),
(29, 'Chesumei', CURRENT_TIMESTAMP, NULL, NULL),
(29, 'Emgwen', CURRENT_TIMESTAMP, NULL, NULL),
(29, 'Mosop', CURRENT_TIMESTAMP, NULL, NULL),

-- Baringo County (30)
(30, 'Baringo North', CURRENT_TIMESTAMP, NULL, NULL),
(30, 'Baringo Central', CURRENT_TIMESTAMP, NULL, NULL),
(30, 'Baringo South', CURRENT_TIMESTAMP, NULL, NULL),
(30, 'Mogotio', CURRENT_TIMESTAMP, NULL, NULL),
(30, 'Eldama Ravine', CURRENT_TIMESTAMP, NULL, NULL),
(30, 'Tiaty East', CURRENT_TIMESTAMP, NULL, NULL),
(30, 'Tiaty West', CURRENT_TIMESTAMP, NULL, NULL),

-- Laikipia County (31)
(31, 'Laikipia West', CURRENT_TIMESTAMP, NULL, NULL),
(31, 'Laikipia East', CURRENT_TIMESTAMP, NULL, NULL),
(31, 'Laikipia North', CURRENT_TIMESTAMP, NULL, NULL),

-- Nakuru County (32)
(32, 'Molo', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Njoro', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Naivasha', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Gilgil', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Kuresoi South', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Kuresoi North', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Subukia', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Rongai', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Bahati', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Nakuru Town West', CURRENT_TIMESTAMP, NULL, NULL),
(32, 'Nakuru Town East', CURRENT_TIMESTAMP, NULL, NULL),

-- Narok County (33)
(33, 'Kilgoris', CURRENT_TIMESTAMP, NULL, NULL),
(33, 'Emurua Dikirr', CURRENT_TIMESTAMP, NULL, NULL),
(33, 'Narok North', CURRENT_TIMESTAMP, NULL, NULL),
(33, 'Narok East', CURRENT_TIMESTAMP, NULL, NULL),
(33, 'Narok South', CURRENT_TIMESTAMP, NULL, NULL),
(33, 'Narok West', CURRENT_TIMESTAMP, NULL, NULL);

-- Kajiado County (34)
(34, 'Kajiado Central', CURRENT_TIMESTAMP, NULL, NULL),
(34, 'Kajiado North', CURRENT_TIMESTAMP, NULL, NULL),
(34, 'Kajiado South', CURRENT_TIMESTAMP, NULL, NULL),
(34, 'Kajiado East', CURRENT_TIMESTAMP, NULL, NULL),
(34, 'Kajiado West', CURRENT_TIMESTAMP, NULL, NULL),

-- Kericho County (35)
(35, 'Ainamoi', CURRENT_TIMESTAMP, NULL, NULL),
(35, 'Bureti', CURRENT_TIMESTAMP, NULL, NULL),
(35, 'Belgut', CURRENT_TIMESTAMP, NULL, NULL),
(35, 'Sigowet/Soin', CURRENT_TIMESTAMP, NULL, NULL),
(35, 'Kipkelion West', CURRENT_TIMESTAMP, NULL, NULL),
(35, 'Kipkelion East', CURRENT_TIMESTAMP, NULL, NULL),

-- Bomet County (36)
(36, 'Sotik', CURRENT_TIMESTAMP, NULL, NULL),
(36, 'Chepalungu', CURRENT_TIMESTAMP, NULL, NULL),
(36, 'Bomet East', CURRENT_TIMESTAMP, NULL, NULL),
(36, 'Bomet Central', CURRENT_TIMESTAMP, NULL, NULL),
(36, 'Konoin', CURRENT_TIMESTAMP, NULL, NULL),

-- Kakamega County (37)
(37, 'Lugari', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Likuyani', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Malava', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Lurambi', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Navakholo', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Mumias West', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Mumias East', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Matungu', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Butere', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Khwisero', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Shinyalu', CURRENT_TIMESTAMP, NULL, NULL),
(37, 'Ikolomani', CURRENT_TIMESTAMP, NULL, NULL),

-- Vihiga County (38)
(38, 'Vihiga', CURRENT_TIMESTAMP, NULL, NULL),
(38, 'Sabatia', CURRENT_TIMESTAMP, NULL, NULL),
(38, 'Hamisi', CURRENT_TIMESTAMP, NULL, NULL),
(38, 'Luanda', CURRENT_TIMESTAMP, NULL, NULL),
(38, 'Emuhaya', CURRENT_TIMESTAMP, NULL, NULL),

-- Bungoma County (39)
(39, 'Mt. Elgon', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Sirisia', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Kabuchai', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Bumula', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Kanduyi', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Webuye East', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Webuye West', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Kimilili', CURRENT_TIMESTAMP, NULL, NULL),
(39, 'Tongaren', CURRENT_TIMESTAMP, NULL, NULL),

-- Busia County (40)
(40, 'Teso North', CURRENT_TIMESTAMP, NULL, NULL),
(40, 'Teso South', CURRENT_TIMESTAMP, NULL, NULL),
(40, 'Nambale', CURRENT_TIMESTAMP, NULL, NULL),
(40, 'Matayos', CURRENT_TIMESTAMP, NULL, NULL),
(40, 'Butula', CURRENT_TIMESTAMP, NULL, NULL),
(40, 'Funyula', CURRENT_TIMESTAMP, NULL, NULL),
(40, 'Budalangi', CURRENT_TIMESTAMP, NULL, NULL),

-- Siaya County (41)
(41, 'Ugenya', CURRENT_TIMESTAMP, NULL, NULL),
(41, 'Ugunja', CURRENT_TIMESTAMP, NULL, NULL),
(41, 'Alego Usonga', CURRENT_TIMESTAMP, NULL, NULL),
(41, 'Gem', CURRENT_TIMESTAMP, NULL, NULL),
(41, 'Bondo', CURRENT_TIMESTAMP, NULL, NULL),
(41, 'Rarieda', CURRENT_TIMESTAMP, NULL, NULL),

-- Kisumu County (42)
(42, 'Kisumu East', CURRENT_TIMESTAMP, NULL, NULL),
(42, 'Kisumu West', CURRENT_TIMESTAMP, NULL, NULL),
(42, 'Kisumu Central', CURRENT_TIMESTAMP, NULL, NULL),
(42, 'Seme', CURRENT_TIMESTAMP, NULL, NULL),
(42, 'Nyando', CURRENT_TIMESTAMP, NULL, NULL),
(42, 'Muhoroni', CURRENT_TIMESTAMP, NULL, NULL),
(42, 'Nyakach', CURRENT_TIMESTAMP, NULL, NULL),

-- Homa Bay County (43)
(43, 'Kasipul', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Kabondo Kasipul', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Karachuonyo', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Rangwe', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Homa Bay Town', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Ndhiwa', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Mbita', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Suba South', CURRENT_TIMESTAMP, NULL, NULL),
(43, 'Suba North', CURRENT_TIMESTAMP, NULL, NULL),

-- Migori County (44)
(44, 'Rongo', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Awendo', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Suna East', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Suna West', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Uriri', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Nyatike', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Kuria East', CURRENT_TIMESTAMP, NULL, NULL),
(44, 'Kuria West', CURRENT_TIMESTAMP, NULL, NULL),

-- Kisii County (45)
(45, 'Bonchari', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'South Mugirango', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Bomachoge Borabu', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Bobasi', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Bomachoge Chache', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Nyaribari Masaba', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Nyaribari Chache', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Kitutu Chache North', CURRENT_TIMESTAMP, NULL, NULL),
(45, 'Kitutu Chache South', CURRENT_TIMESTAMP, NULL, NULL),

-- Nyamira County (46)
(46, 'Kitutu Masaba', CURRENT_TIMESTAMP, NULL, NULL),
(46, 'West Mugirango', CURRENT_TIMESTAMP, NULL, NULL),
(46, 'North Mugirango', CURRENT_TIMESTAMP, NULL, NULL),
(46, 'Borabu', CURRENT_TIMESTAMP, NULL, NULL),

-- Nairobi County (47)
(47, 'Westlands', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Dagoretti North', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Dagoretti South', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Langata', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Kibra', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Roysambu', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Kasarani', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Ruaraka', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Embakasi South', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Embakasi North', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Embakasi Central', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Embakasi East', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Embakasi West', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Makadara', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Kamukunji', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Starehe', CURRENT_TIMESTAMP, NULL, NULL),
(47, 'Mathare', CURRENT_TIMESTAMP, NULL, NULL);